### ISSUE TITLE
nft-bam

### ISSUE THREAD

**Issue by edmundmiller** [askimed/nf-test-plugins#1]
A plugin that you could do something like pull the header from the bam file using samtools or some Java library.

**Comment by nvnieuwk** [comment]
see #2 :)

**Comment by lukfor** [comment]
The `nft-bam` plugin is now released 🎉 Well done @nvnieuwk! Thanks 🙏

btw: Maybe we should mention it somewhere in the nf-test documentation and link to https://nvnieuwk.github.io/nft-bam/latest/
